name       : partio
version    : 1.14.0
release    : 2
source     :
    - https://github.com/wdas/partio/archive/v1.14.0.tar.gz : f98874b781e92ab9b5d0575cabc437d27274cd91cb581f80960918efa491f902
homepage   : https://partio.us/
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : A library for particle IO and manipulation
description: |
    C++ (with python bindings) library for easily reading/writing/manipulating common animation particle formats such as PDB, BGEO, PTC.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(python3)
    - swig
setup      : |
    %patch -p1 < $pkgfiles/libpartio-soname.patch
    %patch -p1 < $pkgfiles/findpython.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
